apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nbforge-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "nbforge-ip"  # Optional: if you've reserved a static IP
    networking.gke.io/managed-certificates: "nbforge-certificate"  # Optional: if using GKE managed certificates
    networking.gke.io/v1beta1.FrontendConfig: "nbforge-frontend-config"  # Optional: for advanced load balancer config
spec:
  rules:
  - host: demo.nbforge.com  # Replace with your domain
    http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      - path: /redoc
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      - path: /openapi.json
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
---
# Optional: Create a managed certificate (only if you're using Google-managed certificates)
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: nbforge-certificate
spec:
  domains:
  - demo.nbforge.com  # Replace with your domain
---
# Optional: Advanced load balancer configuration
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: nbforge-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  # sslPolicy: nbforge-ssl-policy  # Optional: reference to a custom SSL policy 